// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTfWcyTTCotSef1LV2pKG4QxgAUXFCWU',
    appId: '1:669279025672:web:1b29474ef075925bdc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    authDomain: 'fruit-hub-ae74c.firebaseapp.com',
    databaseURL: 'https://fruit-hub-ae74c-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    measurementId: 'G-2606QHC8Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcpZDHXSBb-DTUajK0i2DrW_V8d1mpAMM',
    appId: '1:669279025672:android:5a9490ac776fdda4dc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    databaseURL: 'https://fruit-hub-ae74c-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQiUA303Vj06Nn3qZFfDNRhI0BmBkQctY',
    appId: '1:669279025672:ios:d2642c8ae751f4dddc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    databaseURL: 'https://fruit-hub-ae74c-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    androidClientId: '669279025672-rl8em3aujg0q5kn4gv74cie8r6c71c7d.apps.googleusercontent.com',
    iosClientId: '669279025672-hl2upj4lk2qqle1jegb262cm82egkhkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQiUA303Vj06Nn3qZFfDNRhI0BmBkQctY',
    appId: '1:669279025672:ios:d2642c8ae751f4dddc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    databaseURL: 'https://fruit-hub-ae74c-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    androidClientId: '669279025672-rl8em3aujg0q5kn4gv74cie8r6c71c7d.apps.googleusercontent.com',
    iosClientId: '669279025672-hl2upj4lk2qqle1jegb262cm82egkhkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaTfWcyTTCotSef1LV2pKG4QxgAUXFCWU',
    appId: '1:669279025672:web:328571263d09ac8edc6fbd',
    messagingSenderId: '669279025672',
    projectId: 'fruit-hub-ae74c',
    authDomain: 'fruit-hub-ae74c.firebaseapp.com',
    databaseURL: 'https://fruit-hub-ae74c-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-hub-ae74c.firebasestorage.app',
    measurementId: 'G-LZN1X2YRJ3',
  );
}
